server:
  port: 4040

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # Ruta al natural-service
        - id: natural-service
          uri: lb://NATURAL-SERVICE
          predicates:
            - Path=/api/natural/**

        # Ruta al report-service
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/report/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
