spring:
  application:
    name: natural-service
  datasource:
    url: jdbc:postgresql://localhost:5432/naturalmedic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
